-- Optional: tables for Claude Effect real data (injuries + H2H).
-- Run in Supabase SQL Editor if you want CSI and NM from live data.

-- Injuries: used by lib/api-sports/services/injury-sync (sync + calculateInjuryImpact)
create table if not exists public.injuries (
  id bigint generated by default as identity primary key,
  player_name text not null,
  team_name text not null,
  sport text not null default 'nfl',
  status text,
  injury_type text,
  position text,
  severity text,
  is_starter boolean default false,
  scraped_at timestamptz default now(),
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  unique (player_name, team_name)
);

create index if not exists injuries_team_sport on public.injuries (team_name, sport);

-- H2H history: used by lib/api-sports/services/h2h-sync (sync + calculateNarrativeMomentum)
create table if not exists public.h2h_history (
  id bigint generated by default as identity primary key,
  game_id text not null unique,
  sport text not null,
  home_team_id bigint,
  away_team_id bigint,
  home_team_name text not null,
  away_team_name text not null,
  date timestamptz not null,
  home_score int not null default 0,
  away_score int not null default 0,
  winner text,
  spread numeric,
  total numeric,
  home_covered boolean,
  over_hit boolean,
  synced_at timestamptz default now(),
  created_at timestamptz default now()
);

create index if not exists h2h_history_teams_date on public.h2h_history (home_team_name, away_team_name, date desc);

-- RLS: allow service role to do everything (backend only)
alter table public.injuries enable row level security;
alter table public.h2h_history enable row level security;

create policy "Service role full access injuries" on public.injuries
  for all using (true) with check (true);

create policy "Service role full access h2h_history" on public.h2h_history
  for all using (true) with check (true);
