/**
 * Setup Kalshi via Local Agent
 * Scans repo for Kalshi info and passes to local-agent for installation
 */

import 'dotenv/config';
import * as fs from 'fs';
import * as path from 'path';

const LOCAL_AGENT_URL = process.env.LOCAL_AGENT_URL || 'http://localhost:3847';
const ALPHA_HUNTER_DIR = path.join(__dirname, '..');

interface KalshiConfig {
  apiKeyId?: string;
  privateKey?: string;
  env?: 'demo' | 'production';
  anthropicKey?: string;
  supabaseUrl?: string;
  supabaseKey?: string;
  prognoUrl?: string;
  botApiKey?: string;
}

async function scanRepoForKalshiInfo(): Promise<KalshiConfig> {
  console.log('🔍 Scanning repository for Kalshi configuration...\n');

  const config: KalshiConfig = {};

  // Check .env.local file
  const envLocalPath = path.join(ALPHA_HUNTER_DIR, '.env.local');
  if (fs.existsSync(envLocalPath)) {
    console.log('📄 Found .env.local file');
    const envContent = fs.readFileSync(envLocalPath, 'utf-8');
    
    const getEnvVar = (key: string): string | undefined => {
      const match = envContent.match(new RegExp(`^${key}=(.+)$`, 'm'));
      return match ? match[1].trim() : undefined;
    };

    config.apiKeyId = getEnvVar('KALSHI_API_KEY_ID');
    config.privateKey = getEnvVar('KALSHI_PRIVATE_KEY');
    config.env = (getEnvVar('KALSHI_ENV') as 'demo' | 'production') || 'demo';
    config.anthropicKey = getEnvVar('ANTHROPIC_API_KEY');
    config.supabaseUrl = getEnvVar('NEXT_PUBLIC_SUPABASE_URL');
    config.supabaseKey = getEnvVar('SUPABASE_SERVICE_ROLE_KEY');
    config.prognoUrl = getEnvVar('PROGNO_BASE_URL');
    config.botApiKey = getEnvVar('BOT_API_KEY');
  }

  // Check .env.example for template
  const envExamplePath = path.join(ALPHA_HUNTER_DIR, '.env.example');
  if (fs.existsSync(envExamplePath)) {
    console.log('📄 Found .env.example template');
  }

  // Check KALSHI_START_GUIDE.md for instructions
  const guidePath = path.join(ALPHA_HUNTER_DIR, 'KALSHI_START_GUIDE.md');
  if (fs.existsSync(guidePath)) {
    console.log('📄 Found KALSHI_START_GUIDE.md');
  }

  return config;
}

async function sendToLocalAgent(config: KalshiConfig): Promise<void> {
  console.log('\n📤 Sending Kalshi setup to Local Agent...\n');

  // Check if local-agent is running
  try {
    const healthCheck = await fetch(`${LOCAL_AGENT_URL}/health`);
    if (!healthCheck.ok) {
      throw new Error('Local Agent not responding');
    }
    console.log('✅ Local Agent is running\n');
  } catch (error) {
    console.error('❌ Local Agent is not running!');
    console.error('   Start it with: cd apps/local-agent && pnpm dev\n');
    throw error;
  }

  // Create .env.local content
  const envContent = `# Alpha Hunter - Kalshi Configuration
# Generated by setup-kalshi-via-agent.ts

# === KALSHI PREDICTION MARKETS ===
${config.apiKeyId ? `KALSHI_API_KEY_ID=${config.apiKeyId}` : 'KALSHI_API_KEY_ID='}
${config.privateKey ? `KALSHI_PRIVATE_KEY=${config.privateKey}` : 'KALSHI_PRIVATE_KEY='}
KALSHI_ENV=${config.env || 'demo'}

# === REQUIRED FOR AI ANALYSIS ===
${config.anthropicKey ? `ANTHROPIC_API_KEY=${config.anthropicKey}` : 'ANTHROPIC_API_KEY='}

# === REQUIRED FOR DATA PERSISTENCE ===
${config.supabaseUrl ? `NEXT_PUBLIC_SUPABASE_URL=${config.supabaseUrl}` : 'NEXT_PUBLIC_SUPABASE_URL='}
${config.supabaseKey ? `SUPABASE_SERVICE_ROLE_KEY=${config.supabaseKey}` : 'SUPABASE_SERVICE_ROLE_KEY='}

# === OPTIONAL: PROGNO INTEGRATION ===
${config.prognoUrl ? `PROGNO_BASE_URL=${config.prognoUrl}` : 'PROGNO_BASE_URL=https://prognoultimatev2-cevict-projects.vercel.app'}
${config.botApiKey ? `BOT_API_KEY=${config.botApiKey}` : 'BOT_API_KEY='}

# === RISK MANAGEMENT ===
DAILY_PROFIT_TARGET=250
MAX_DAILY_LOSS=100
MAX_SINGLE_TRADE=10
MAX_OPEN_POSITIONS=5
MIN_CONFIDENCE=70
MIN_EXPECTED_VALUE=8

# === EXECUTION SETTINGS ===
AUTO_EXECUTE=false
`;

  // Write .env.local file via local-agent
  const envLocalPath = path.join(ALPHA_HUNTER_DIR, '.env.local');
  const relativePath = path.relative(process.cwd(), envLocalPath);

  try {
    const writeResponse = await fetch(`${LOCAL_AGENT_URL}/file/write`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        path: envLocalPath,
        content: envContent,
      }),
    });

    const writeResult = await writeResponse.json();
    if (writeResult.success) {
      console.log('✅ Created/updated .env.local file');
    } else {
      console.error('❌ Failed to write .env.local:', writeResult.error);
    }
  } catch (error: any) {
    console.error('❌ Error writing file:', error.message);
  }

  // Install dependencies via local-agent
  console.log('\n📦 Installing dependencies...');
  try {
    const installResponse = await fetch(`${LOCAL_AGENT_URL}/execute`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        command: 'pnpm install',
        cwd: ALPHA_HUNTER_DIR,
      }),
    });

    const installResult = await installResponse.json();
    if (installResult.success) {
      console.log('✅ Dependencies installed');
      if (installResult.stdout) {
        console.log(installResult.stdout);
      }
    } else {
      console.error('❌ Failed to install dependencies:', installResult.error);
    }
  } catch (error: any) {
    console.error('❌ Error installing dependencies:', error.message);
  }

  // Test connection
  console.log('\n🧪 Testing Kalshi connection...');
  try {
    const testResponse = await fetch(`${LOCAL_AGENT_URL}/execute`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        command: 'pnpm run test',
        cwd: ALPHA_HUNTER_DIR,
      }),
    });

    const testResult = await testResponse.json();
    if (testResult.success) {
      console.log('✅ Test completed');
      if (testResult.stdout) {
        console.log(testResult.stdout);
      }
    } else {
      console.warn('⚠️ Test had issues:', testResult.error);
    }
  } catch (error: any) {
    console.error('❌ Error running tests:', error.message);
  }
}

async function main() {
  console.log(`
╔══════════════════════════════════════════════════════════════╗
║     🎯 KALSHI SETUP VIA LOCAL AGENT                          ║
║                                                              ║
║  Scans repo for Kalshi info and configures via local-agent  ║
╚══════════════════════════════════════════════════════════════╝
  `);

  try {
    // Step 1: Scan repo
    const config = await scanRepoForKalshiInfo();

    console.log('\n📋 Found Configuration:');
    console.log(`   KALSHI_API_KEY_ID: ${config.apiKeyId ? '✅ Set' : '❌ Not set'}`);
    console.log(`   KALSHI_PRIVATE_KEY: ${config.privateKey ? '✅ Set' : '❌ Not set'}`);
    console.log(`   KALSHI_ENV: ${config.env || 'demo'}`);
    console.log(`   ANTHROPIC_API_KEY: ${config.anthropicKey ? '✅ Set' : '❌ Not set'}`);
    console.log(`   SUPABASE_URL: ${config.supabaseUrl ? '✅ Set' : '❌ Not set'}`);

    // Step 2: Send to local-agent
    await sendToLocalAgent(config);

    console.log(`
╔══════════════════════════════════════════════════════════════╗
║                    ✅ SETUP COMPLETE                          ║
╚══════════════════════════════════════════════════════════════╝

📝 Next Steps:
   1. Review .env.local file and add any missing credentials
   2. Start Kalshi trader: pnpm run kalshi
   3. Monitor performance: pnpm run report

🚀 Ready to start? Run: pnpm run kalshi
    `);

  } catch (error: any) {
    console.error('\n❌ Setup failed:', error.message);
    process.exit(1);
  }
}

main();

