"use client";

import { useEffect, useState, useRef } from "react";
import { FishActivityPrediction, predictFishActivityMultiDay } from "./fish-activity-predictor";
import { getCoordinatesFromLocation, getTidePredictionsForLocation } from "./free-data-fetcher";

export default function FishActivityPage() {
  const [location, setLocation] = useState("Panama City, FL");
  const [days, setDays] = useState(7);
  const [loading, setLoading] = useState(false);
  const [predictions, setPredictions] = useState<FishActivityPrediction[]>([]);
  const [error, setError] = useState<string | null>(null);
  const [includeTides, setIncludeTides] = useState(true);
  const isFetchingRef = useRef(false);

  useEffect(() => {
    const savedLocation = localStorage.getItem('fish_location');
    if (savedLocation) setLocation(savedLocation);
  }, []);

  async function fetchFishActivity() {
    // Prevent multiple simultaneous calls
    if (isFetchingRef.current || loading) {
      return;
    }

    isFetchingRef.current = true;
    setLoading(true);
    setError(null);

    try {
      // Get coordinates
      const coords = await getCoordinatesFromLocation(location);
      if (!coords) {
        throw new Error('Could not find location. Please try a more specific location.');
      }

      // Get tide data if requested
      let tideDataByDate: Record<string, { time: Date; height: number; type: 'High' | 'Low' }[]> = {};

      if (includeTides) {
        try {
          const tideData = await getTidePredictionsForLocation(coords, days);
          tideData.forEach((tide: any) => {
            const dateKey = tide.time.toISOString().split('T')[0];
            if (!tideDataByDate[dateKey]) tideDataByDate[dateKey] = [];
            tideDataByDate[dateKey].push(tide);
          });
        } catch (tideError) {
          console.log('Tide data unavailable, continuing without it:', tideError);
        }
      }

      // Generate predictions for each day
      const startDate = new Date();
      const fishingConditions = {
        location: { name: location, coordinates: coords },
        tides: tideDataByDate ? Object.values(tideDataByDate).flat().map(tide => ({
        ...tide,
        type: tide.type.toLowerCase() as 'high' | 'low'
      })) : [],
        weather: { temperature: 70, humidity: 50, windSpeed: 10, windDirection: "NW", pressure: 30.15, conditions: "Clear" }, // Mock weather data
        moonPhase: "full",
        sunrise: new Date(startDate.setHours(6, 0, 0, 0)),
        sunset: new Date(startDate.setHours(18, 0, 0, 0))
      };
      const results = await predictFishActivityMultiDay(fishingConditions, days);

      setPredictions(results.predictions);
      localStorage.setItem('fish_location', location);
    } catch (err: any) {
      setError(err.message || 'Failed to predict fish activity');
      console.error('Fish activity error:', err);
    } finally {
      setLoading(false);
      isFetchingRef.current = false;
    }
  }

  function getScoreColor(score: number): string {
    if (score >= 80) return "#00ffaa";
    if (score >= 65) return "#00b4ff";
    if (score >= 50) return "#ffaa00";
    return "#ff6666";
  }

  function getScoreLabel(score: number): string {
    if (score >= 80) return "Excellent";
    if (score >= 65) return "Good";
    if (score >= 50) return "Fair";
    return "Poor";
  }

  function sharePredictions() {
    if (predictions.length === 0) return;

    const bestDay = predictions.sort((a, b) => b.overallScore - a.overallScore)[0];
    const shareText = `🎣 PROGNO Fish Activity Predictions for ${location}\n\nBest Day: ${new Date(bestDay.date).toLocaleDateString('en-US', { weekday: 'long', month: 'long', day: 'numeric' })}\nScore: ${bestDay.overallScore}% - ${getScoreLabel(bestDay.overallScore)}\n\nBest Times:\n${bestDay.timeSlots.slice(0, 3).map(t => `• ${t.startTime.toLocaleTimeString()} - ${t.endTime.toLocaleTimeString()} | Score: ${t.score}%`).join('\n')}\n\nGenerated by PROGNO Prediction Engine\n\nTry it: [Your URL]`;

    if (navigator.share) {
      navigator.share({ text: shareText }).catch(() => {
        navigator.clipboard.writeText(shareText);
        alert('✅ Copied to clipboard!');
      });
    } else {
      navigator.clipboard.writeText(shareText);
      alert('✅ Copied to clipboard!');
    }
  }

  return (
    <div style={{ padding: "40px", color: "white", fontFamily: "sans-serif", background: "#0a0a0a", minHeight: "100vh" }}>
      <div style={{ maxWidth: "1400px", margin: "0 auto" }}>
        <div style={{ marginBottom: "30px", display: "flex", justifyContent: "space-between", alignItems: "start" }}>
          <div>
            <h1 style={{ fontSize: "32px", marginBottom: "5px", background: "linear-gradient(90deg, #00ffaa, #00b4ff)", WebkitBackgroundClip: "text", WebkitTextFillColor: "transparent" }}>
              🎣 FISH ACTIVITY PREDICTIONS
            </h1>
            <p style={{ color: "#888", fontSize: "14px" }}>
              Predict best fishing times using solunar theory, moon phases, and tide data
            </p>
          </div>
          {predictions.length > 0 && (
            <button
              onClick={sharePredictions}
              style={{
                padding: "10px 20px",
                background: "linear-gradient(90deg, #00ffaa, #00b4ff)",
                color: "#000",
                border: "none",
                borderRadius: "8px",
                cursor: "pointer",
                fontSize: "14px",
                fontWeight: "bold",
              }}
            >
              📤 Share Predictions
            </button>
          )}
        </div>

        {/* Controls */}
        <div style={{ background: "#111", padding: "30px", borderRadius: "12px", marginBottom: "30px" }}>
          <div style={{ display: "grid", gridTemplateColumns: "repeat(3, 1fr)", gap: "20px", marginBottom: "20px" }}>
            <div>
              <label style={{ display: "block", marginBottom: "8px", color: "#aaa" }}>Location</label>
              <input
                type="text"
                value={location}
                onChange={(e) => setLocation(e.target.value)}
                placeholder="Panama City, FL"
                style={{ padding: "12px", width: "100%", background: "#222", color: "white", border: "1px solid #333", borderRadius: "6px" }}
                onKeyPress={(e) => e.key === 'Enter' && fetchFishActivity()}
              />
            </div>
            <div>
              <label style={{ display: "block", marginBottom: "8px", color: "#aaa" }}>Days</label>
              <input
                type="number"
                value={days}
                onChange={(e) => setDays(Math.max(1, Math.min(14, parseInt(e.target.value) || 7)))}
                min="1"
                max="14"
                style={{ padding: "12px", width: "100%", background: "#222", color: "white", border: "1px solid #333", borderRadius: "6px" }}
              />
            </div>
            <div style={{ display: "flex", alignItems: "flex-end" }}>
              <button
                onClick={fetchFishActivity}
                disabled={loading}
                style={{
                  width: "100%",
                  padding: "12px 24px",
                  background: loading ? "#333" : "linear-gradient(90deg, #00ffaa, #00b4ff)",
                  color: "black",
                  fontSize: "16px",
                  fontWeight: "bold",
                  borderRadius: "8px",
                  border: "none",
                  cursor: loading ? "not-allowed" : "pointer",
                }}
              >
                {loading ? "🎣 Analyzing..." : "🔮 Predict Fish Activity"}
              </button>
            </div>
          </div>

          <label style={{ display: "flex", alignItems: "center", gap: "8px", cursor: "pointer" }}>
            <input
              type="checkbox"
              checked={includeTides}
              onChange={(e) => setIncludeTides(e.target.checked)}
              style={{ width: "18px", height: "18px" }}
            />
            <span style={{ color: "#aaa", fontSize: "14px" }}>Include tide data for better predictions</span>
          </label>
        </div>

        {/* Error */}
        {error && (
          <div style={{ background: "#330000", padding: "20px", borderRadius: "12px", marginBottom: "30px", border: "1px solid #ff4444" }}>
            <p style={{ color: "#ff6666", margin: 0 }}>❌ {error}</p>
          </div>
        )}

        {/* Results */}
        {predictions.length > 0 && (
          <div>
            {/* Summary */}
            <div style={{ background: "#111", padding: "30px", borderRadius: "12px", marginBottom: "30px", border: "1px solid #333" }}>
              <h2 style={{ fontSize: "24px", marginBottom: "20px", color: "#00ffaa" }}>📊 Summary</h2>
              <div style={{ display: "grid", gridTemplateColumns: "repeat(4, 1fr)", gap: "15px" }}>
                <div style={{ background: "#222", padding: "15px", borderRadius: "8px", textAlign: "center" }}>
                  <div style={{ color: "#888", fontSize: "12px", marginBottom: "5px" }}>Days Analyzed</div>
                  <div style={{ color: "#00ffaa", fontSize: "24px", fontWeight: "bold" }}>{predictions.length}</div>
                </div>
                <div style={{ background: "#222", padding: "15px", borderRadius: "8px", textAlign: "center" }}>
                  <div style={{ color: "#888", fontSize: "12px", marginBottom: "5px" }}>Avg Score</div>
                  <div style={{ color: "#00b4ff", fontSize: "24px", fontWeight: "bold" }}>
                    {Math.round(predictions.reduce((sum, p) => sum + p.overallScore, 0) / predictions.length)}%
                  </div>
                </div>
                <div style={{ background: "#222", padding: "15px", borderRadius: "8px", textAlign: "center" }}>
                  <div style={{ color: "#888", fontSize: "12px", marginBottom: "5px" }}>Best Day</div>
                  <div style={{ color: "#00ffaa", fontSize: "18px", fontWeight: "bold" }}>
                    {predictions.sort((a, b) => b.overallScore - a.overallScore)[0]?.date?.toLocaleDateString() || 'N/A'}
                  </div>
                </div>
                <div style={{ background: "#222", padding: "15px", borderRadius: "8px", textAlign: "center" }}>
                  <div style={{ color: "#888", fontSize: "12px", marginBottom: "5px" }}>Best Score</div>
                  <div style={{ color: "#00ffaa", fontSize: "24px", fontWeight: "bold" }}>
                    {Math.max(...predictions.map(p => p.overallScore))}%
                  </div>
                </div>
              </div>
            </div>

            {/* Daily Predictions */}
            {predictions.map((prediction, idx) => (
              <div key={idx} style={{ background: "#111", padding: "30px", borderRadius: "12px", marginBottom: "20px", border: "1px solid #333" }}>
                <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: "20px" }}>
                  <div>
                    <h3 style={{ fontSize: "22px", margin: "0 0 5px 0", color: "#00b4ff" }}>
                      {new Date(prediction.date).toLocaleDateString('en-US', { weekday: 'long', month: 'long', day: 'numeric' })}
                    </h3>
                    <p style={{ color: "#888", margin: 0, fontSize: "14px" }}>{location}</p>
                  </div>
                  <div style={{ textAlign: "right" }}>
                    <div style={{
                      fontSize: "32px",
                      fontWeight: "bold",
                      color: getScoreColor(prediction.overallScore),
                      marginBottom: "5px"
                    }}>
                      {prediction.overallScore}%
                    </div>
                    <div style={{ color: getScoreColor(prediction.overallScore), fontSize: "14px" }}>
                      {getScoreLabel(prediction.overallScore)}
                    </div>
                  </div>
                </div>

                {/* Moon Phase */}
                <div style={{ background: "#1a1a1a", padding: "15px", borderRadius: "8px", marginBottom: "20px" }}>
                  <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center" }}>
                    <div>
                      <div style={{ color: "#888", fontSize: "12px", marginBottom: "5px" }}>Moon Phase</div>
                      <div style={{ color: "#fff", fontSize: "16px", fontWeight: "bold" }}>
                        Full Moon (100% illuminated)
                      </div>
                      <div style={{ color: "#888", fontSize: "12px" }}>Optimal fishing during peak hours</div>
                      <div style={{ color: "#888", fontSize: "12px" }}>Best activity: Dawn & Dusk</div>
                    </div>
                  </div>
                </div>

                {/* Best Times */}
                <div style={{ marginBottom: "20px" }}>
                  <h4 style={{ fontSize: "16px", marginBottom: "15px", color: "#00ffaa" }}>🎣 Best Fishing Times</h4>
                  <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(250px, 1fr))", gap: "10px" }}>
                    {prediction.timeSlots.map((time, i) => (
                      <div
                        key={i}
                        style={{
                          background: "rgba(0, 255, 170, 0.1)",
                          border: "1px solid #00ffaa",
                          padding: "12px",
                          borderRadius: "6px"
                        }}
                      >
                        <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: "5px" }}>
                          <span style={{ color: "#00ffaa", fontWeight: "bold" }}>{time.startTime.toLocaleTimeString()}</span>
                          <span style={{ color: "#00ffaa", fontSize: "18px", fontWeight: "bold" }}>{time.score}%</span>
                        </div>
                        <div style={{ color: "#aaa", fontSize: "12px" }}>{time.description}</div>
                      </div>
                    ))}
                  </div>
                </div>

                {/* Solunar Periods */}
                <div style={{ marginBottom: "20px" }}>
                  <h4 style={{ fontSize: "16px", marginBottom: "15px", color: "#00b4ff" }}>🌙 Peak Activity Periods</h4>
                  <div style={{ display: "grid", gridTemplateColumns: "repeat(2, 1fr)", gap: "15px" }}>
                    <div>
                      <div style={{ color: "#888", fontSize: "12px", marginBottom: "8px" }}>Major Periods (Best)</div>
                      {prediction.timeSlots.filter((slot: any) => slot.score >= 80).map((period: any, i: number) => (
                        <div key={i} style={{ background: "#1a1a1a", padding: "10px", borderRadius: "6px", marginBottom: "8px" }}>
                          <div style={{ color: "#00b4ff", fontWeight: "bold" }}>
                            {period.startTime.toLocaleTimeString()} - {period.endTime.toLocaleTimeString()}
                          </div>
                          <div style={{ color: "#888", fontSize: "12px" }}>Score: {period.score}%</div>
                        </div>
                      ))}
                    </div>
                    <div>
                      <div style={{ color: "#888", fontSize: "12px", marginBottom: "8px" }}>Minor Periods (Good)</div>
                      {prediction.timeSlots.filter((slot: any) => slot.score >= 60 && slot.score < 80).map((period: any, i: number) => (
                        <div key={i} style={{ background: "#1a1a1a", padding: "10px", borderRadius: "6px", marginBottom: "8px" }}>
                          <div style={{ color: "#888", fontWeight: "bold" }}>
                            {period.startTime.toLocaleTimeString()} - {period.endTime.toLocaleTimeString()}
                          </div>
                          <div style={{ color: "#888", fontSize: "12px" }}>Score: {period.score}%</div>
                        </div>
                      ))}
                    </div>
                  </div>
                </div>

                {/* Tide Information */}
                <div style={{ marginBottom: "20px" }}>
                  <h4 style={{ fontSize: "16px", marginBottom: "15px", color: "#00b4ff" }}>🌊 Tide Information</h4>
                  <div style={{ background: "#1a1a1a", padding: "15px", borderRadius: "8px" }}>
                    <div style={{ color: "#888", fontSize: "14px" }}>
                      Tide conditions can significantly impact fish activity. Check local tide charts for the best fishing times.
                    </div>
                  </div>
                </div>

                {/* Recommendations */}
                <div style={{ background: "rgba(0, 255, 170, 0.1)", border: "1px solid #00ffaa", padding: "15px", borderRadius: "8px" }}>
                  <h4 style={{ fontSize: "16px", marginBottom: "10px", color: "#00ffaa" }}>💡 Recommendations</h4>
                  <ul style={{ margin: 0, paddingLeft: "20px", color: "#aaa" }}>
                    {prediction.recommendations.map((rec, i) => (
                      <li key={i} style={{ marginBottom: "5px" }}>{rec}</li>
                    ))}
                  </ul>
                </div>
              </div>
            ))}
          </div>
        )}
      </div>
    </div>
  );
}

