// Sports and Camping Knowledge Base

// Sports Knowledge
export const SPORTS_KNOWLEDGE: Record<string, string> = {
  'football': 'American football is a team sport played with an oval ball on a rectangular field. The NFL is the premier professional league, with games played on Sundays and Monday nights during the season.',
  'basketball': 'Basketball is played by two teams of five players on a rectangular court. The NBA is the premier professional league, known for high-scoring games and athleticism.',
  'baseball': 'Baseball is a bat-and-ball game played between two teams of nine players. MLB is the premier professional league, with a 162-game regular season.',
  'soccer': 'Soccer (football outside the US) is the world\'s most popular sport, played by two teams of 11 players. Major leagues include the Premier League, La Liga, and MLS.',
  'hockey': 'Ice hockey is played on ice with skates, sticks, and a puck. The NHL is the premier professional league, known for fast-paced, physical play.',
  'tennis': 'Tennis is a racket sport played individually or in pairs. Major tournaments include Wimbledon, US Open, French Open, and Australian Open (the Grand Slams).',
  'golf': 'Golf is a precision club-and-ball sport played on a course. Major tournaments include The Masters, US Open, The Open Championship, and PGA Championship.',
  'olympics': 'The Olympic Games are international multi-sport events held every four years, alternating between Summer and Winter Olympics. They feature athletes from around the world.',
  'super bowl': 'The Super Bowl is the championship game of the NFL, played annually in February. It\'s one of the most-watched television events in the United States.',
  'world cup': 'The FIFA World Cup is the premier international soccer tournament, held every four years. It\'s the most-watched sporting event globally.',
  'nfl': 'The National Football League (NFL) consists of 32 teams divided into two conferences. The season runs from September to February, culminating in the Super Bowl.',
  'nba': 'The National Basketball Association (NBA) has 30 teams. The season runs from October to June, with playoffs determining the champion.',
  'mlb': 'Major League Baseball (MLB) has 30 teams split between the American and National Leagues. The season runs from April to October.',
  'nhl': 'The National Hockey League (NHL) has 32 teams. The season runs from October to June, with the Stanley Cup awarded to the champion.',
  'sports betting': 'Sports betting involves wagering on the outcome of sporting events. It\'s legal in many jurisdictions and includes bets on winners, spreads, totals, and prop bets.',
  'fantasy sports': 'Fantasy sports allow participants to draft teams of real players and compete based on their statistical performance. Popular formats include season-long and daily fantasy.',

  // NCAA / College Sports
  'ncaa': 'The NCAA (National Collegiate Athletic Association) governs college athletics in the United States, organizing championships and setting rules for Division I, II, and III schools.',
  'college football': 'NCAA college football features FBS (Football Bowl Subdivision) and FCS (Football Championship Subdivision). The season runs from late August to January, with bowl games and the College Football Playoff.',
  'college basketball': 'NCAA college basketball season runs from November to April, culminating in March Madness - a 68-team single-elimination tournament to determine the national champion.',
  'march madness': 'March Madness is the NCAA Division I men\'s basketball tournament, featuring 68 teams in a single-elimination bracket. It includes the First Four, Round of 64, Sweet 16, Elite Eight, Final Four, and Championship game.',
  'final four': 'The Final Four is the semifinal round of March Madness, featuring the last four teams remaining in the tournament. It\'s held annually at a predetermined location, typically in early April.',
  'college football playoff': 'The College Football Playoff (CFP) determines the FBS national champion. Four teams are selected by a committee, with semifinals on New Year\'s Day and the championship game in early January.',
  'heisman trophy': 'The Heisman Trophy is awarded annually to the most outstanding player in college football. It\'s considered the most prestigious individual award in college sports.',
  'sec': 'The SEC (Southeastern Conference) is one of the Power 5 conferences in college football and basketball, featuring schools like Alabama, Georgia, LSU, Florida, and Tennessee.',
  'big ten': 'The Big Ten Conference features 14 universities (soon to be 18) including Michigan, Ohio State, Penn State, and Wisconsin. It\'s one of the oldest and most prestigious conferences.',
  'acc': 'The ACC (Atlantic Coast Conference) includes schools like Clemson, Florida State, Duke, North Carolina, and Miami. It\'s known for strong basketball and football programs.',
  'big 12': 'The Big 12 Conference features schools like Texas, Oklahoma, Kansas, and Baylor. It\'s known for high-scoring football games and competitive basketball.',
  'pac-12': 'The Pac-12 Conference (formerly Pac-10) includes West Coast schools like USC, UCLA, Oregon, and Washington. It\'s known for strong academics and athletics.',
  'college football rankings': 'College football rankings include the AP Poll (media) and Coaches Poll. The College Football Playoff Committee releases weekly rankings starting in November to determine playoff participants.',
  'bowl games': 'Bowl games are postseason college football games, typically played in December and January. Major bowls include the Rose Bowl, Sugar Bowl, Orange Bowl, and Cotton Bowl.',
  'ncaa tournament': 'The NCAA Tournament refers to March Madness (basketball) but also includes tournaments for other sports like baseball, softball, volleyball, and soccer.',
  'college sports betting': 'College sports betting is popular, especially for college football and March Madness. Betting includes game lines, totals, futures, and prop bets on individual players.',
  'rivalry games': 'College sports feature intense rivalries like Alabama-Auburn (Iron Bowl), Michigan-Ohio State (The Game), Army-Navy, and Duke-North Carolina (basketball).',
  'college basketball rankings': 'College basketball rankings include the AP Top 25 and Coaches Poll, released weekly during the season. Rankings help determine tournament seeding.',
  'ncaa divisions': 'NCAA has three divisions: Division I (largest schools, most competitive), Division II (mid-size schools), and Division III (smaller schools, no athletic scholarships).',
  'college football season': 'College football season runs from late August/early September through early January. Regular season is 12 games, followed by conference championships and bowl season.',
  'college basketball season': 'College basketball season runs from early November through early April. Regular season includes conference play, followed by conference tournaments and March Madness.',
  'power 5': 'The Power 5 conferences are the SEC, Big Ten, ACC, Big 12, and Pac-12. These conferences have the largest budgets, most resources, and typically the strongest teams.',
  'group of 5': 'The Group of 5 conferences (American, Conference USA, MAC, Mountain West, Sun Belt) are FBS conferences outside the Power 5. They compete for the New Year\'s Six bowl spot.',
  'ncaa championships': 'NCAA championships are held for numerous sports including football, basketball, baseball, softball, soccer, volleyball, track and field, swimming, and many others.',
  'college football national championship': 'The College Football Playoff National Championship game determines the FBS national champion. It\'s played in early January at a neutral site.',
  'march madness bracket': 'March Madness brackets are filled out by millions of fans. The tournament features upsets, Cinderella stories, and dramatic finishes that make it one of the most exciting events in sports.',
  'college football recruiting': 'College football recruiting involves high school players committing to schools. National Signing Day is in February, with early signing period in December.',
  'college basketball recruiting': 'College basketball recruiting involves high school and transfer portal players. Top recruits often become one-and-done players heading to the NBA.',
  'transfer portal': 'The NCAA Transfer Portal allows college athletes to enter their name and transfer to other schools. It has significantly changed college sports, especially football and basketball.',
  'ncaa eligibility': 'NCAA eligibility requires student-athletes to meet academic standards, maintain amateur status, and follow rules regarding benefits, agents, and compensation.',
  'college sports conferences': 'College sports are organized into conferences that schedule games and hold championships. Major conferences include Power 5, Group of 5, and numerous Division I conferences.',
};

// Camping Knowledge
export const CAMPING_KNOWLEDGE: Record<string, string> = {
  'camping': 'Camping involves staying overnight in a tent, RV, or other shelter in natural settings. It requires proper gear, planning, and knowledge of outdoor safety.',
  'camping gear': 'Essential camping gear includes a tent, sleeping bag, sleeping pad, camp stove, cooler, first aid kit, flashlight, and appropriate clothing for the weather.',
  'tent': 'Tents provide shelter while camping. Choose based on capacity (number of people), season (3-season or 4-season), weight (for backpacking), and ease of setup.',
  'camping checklist': 'A camping checklist should include: tent, sleeping bag, sleeping pad, camp stove and fuel, cooler, food and water, first aid kit, flashlight/headlamp, matches/lighter, and appropriate clothing.',
  'campfire safety': 'Campfire safety includes: only building fires in designated areas, keeping fires small, never leaving fires unattended, fully extinguishing fires with water, and checking for fire restrictions.',
  'camping food': 'Camping food should be easy to prepare, non-perishable, and nutritious. Popular options include dehydrated meals, canned goods, trail mix, granola bars, and foods that can be cooked over a campfire or stove.',
  'backpacking': 'Backpacking involves hiking with all gear carried in a backpack. It requires lightweight equipment, careful planning, and knowledge of backcountry skills.',
  'camping tips': 'Camping tips include: arrive early to set up in daylight, check weather forecasts, store food properly to avoid attracting wildlife, follow Leave No Trace principles, and inform others of your plans.',
  'leave no trace': 'Leave No Trace principles include: plan ahead, travel and camp on durable surfaces, dispose of waste properly, leave what you find, minimize campfire impacts, respect wildlife, and be considerate of others.',
  'camping destinations': 'Popular camping destinations include national parks, state parks, national forests, and private campgrounds. Research permits, reservations, and regulations before visiting.',
  'rv camping': 'RV camping involves traveling in a recreational vehicle. It offers more comfort than tent camping but requires knowledge of RV systems, hookups, and campground amenities.',
  'wildlife safety': 'Wildlife safety while camping includes: storing food properly, keeping a clean campsite, making noise while hiking, carrying bear spray in bear country, and knowing how to react to wildlife encounters.',
  'camping weather': 'Check weather forecasts before camping and prepare for changing conditions. Bring appropriate clothing layers, rain gear, and know how to stay warm and dry.',
  'first aid camping': 'A camping first aid kit should include: bandages, antiseptic, pain relievers, tweezers, medical tape, emergency blanket, and any personal medications. Know basic first aid procedures.',
};

