-- REMOVE FAKE DATA FROM LOST_PETS TABLE
-- This identifies and removes pets that were generated by fake scrapers

-- ============================================
-- STEP 1: IDENTIFY FAKE DATA
-- ============================================
-- Check how many fake pets we have
SELECT 
  'Fake pets count' as check_type,
  COUNT(*) as count
FROM lost_pets
WHERE 
  -- Owner name is "Community" (fake scraper pattern)
  owner_name = 'Community'
  OR
  -- Pet name is one of the fake scraper names
  pet_name IN ('Buddy', 'Luna', 'Max', 'Charlie', 'Cooper', 'Rocky', 'Bear', 'Duke', 'Tucker', 'Jack', 'Oliver', 'Bella', 'Lucy', 'Daisy', 'Sadie', 'Molly', 'Bailey', 'Maggie', 'Sophie', 'Chloe', 'Leo', 'Milo', 'Simba', 'Loki', 'Oscar', 'Jasper', 'Tiger', 'Nala', 'Kitty', 'Lily', 'Callie', 'Cleo')
  OR
  -- Description matches fake scraper pattern
  description LIKE 'Friendly % looking for a forever home. Found in %'
  OR description LIKE 'Seen near %, %. %'
  OR
  -- Source URL is from fake scrapers
  source_url LIKE 'https://example.com/%'
  OR source_post_id LIKE '%_sim_%'
  OR
  -- Source platform is from fake scrapers
  source_platform IN ('petharbor', 'facebook', 'instagram', 'tiktok')
  OR
  -- Photo URLs are from fake photo APIs
  photo_url LIKE 'https://images.dog.ceo/%'
  OR photo_url LIKE 'https://cdn2.thecatapi.com/%';

-- ============================================
-- STEP 2: PREVIEW WHAT WILL BE DELETED
-- ============================================
SELECT 
  id,
  pet_name,
  pet_type,
  location_city,
  location_state,
  owner_name,
  description,
  source_platform,
  source_url,
  created_at
FROM lost_pets
WHERE 
  owner_name = 'Community'
  OR
  pet_name IN ('Buddy', 'Luna', 'Max', 'Charlie', 'Cooper', 'Rocky', 'Bear', 'Duke', 'Tucker', 'Jack', 'Oliver', 'Bella', 'Lucy', 'Daisy', 'Sadie', 'Molly', 'Bailey', 'Maggie', 'Sophie', 'Chloe', 'Leo', 'Milo', 'Simba', 'Loki', 'Oscar', 'Jasper', 'Tiger', 'Nala', 'Kitty', 'Lily', 'Callie', 'Cleo')
  OR
  description LIKE 'Friendly % looking for a forever home. Found in %'
  OR description LIKE 'Seen near %, %. %'
  OR
  source_url LIKE 'https://example.com/%'
  OR source_post_id LIKE '%_sim_%'
  OR
  source_platform IN ('petharbor', 'facebook', 'instagram', 'tiktok')
  OR
  photo_url LIKE 'https://images.dog.ceo/%'
  OR photo_url LIKE 'https://cdn2.thecatapi.com/%'
ORDER BY created_at DESC
LIMIT 100;

-- ============================================
-- STEP 3: DELETE FAKE DATA
-- ============================================
-- UNCOMMENT THE LINE BELOW TO ACTUALLY DELETE
-- BACKUP YOUR DATABASE FIRST!

-- DELETE FROM lost_pets
-- WHERE 
--   owner_name = 'Community'
--   OR
--   pet_name IN ('Buddy', 'Luna', 'Max', 'Charlie', 'Cooper', 'Rocky', 'Bear', 'Duke', 'Tucker', 'Jack', 'Oliver', 'Bella', 'Lucy', 'Daisy', 'Sadie', 'Molly', 'Bailey', 'Maggie', 'Sophie', 'Chloe', 'Leo', 'Milo', 'Simba', 'Loki', 'Oscar', 'Jasper', 'Tiger', 'Nala', 'Kitty', 'Lily', 'Callie', 'Cleo')
--   OR
--   description LIKE 'Friendly % looking for a forever home. Found in %'
--   OR description LIKE 'Seen near %, %. %'
--   OR
--   source_url LIKE 'https://example.com/%'
--   OR source_post_id LIKE '%_sim_%'
--   OR
--   source_platform IN ('petharbor', 'facebook', 'instagram', 'tiktok')
--   OR
--   photo_url LIKE 'https://images.dog.ceo/%'
--   OR photo_url LIKE 'https://cdn2.thecatapi.com/%';

-- ============================================
-- STEP 4: VERIFY DELETION
-- ============================================
-- After deletion, check remaining count
SELECT COUNT(*) as remaining_pets FROM lost_pets;

-- Check for any remaining fake patterns
SELECT COUNT(*) as remaining_fake
FROM lost_pets
WHERE 
  owner_name = 'Community'
  OR description LIKE 'Friendly % looking for a forever home. Found in %'
  OR source_url LIKE 'https://example.com/%';
