name: Create Production Builds

on:
  push:
    branches: ['main', 'master', 'gcc-vessels']

jobs:
  build_android:
    type: build
    params:
      platform: android
      profile: production
  build_ios:
    type: build
    params:
      platform: ios
      profile: production
