/**
 * Export Service - PDF cards and CSV export
 * Generate printable betting sheets and data exports
 */

import jsPDF from 'jspdf';
import 'jspdf-autotable';

export interface ExportPick {
  id: string;
  sport: string;
  league?: string;
  game: string;
  pick: string;
  pickType: string;
  odds: number;
  confidence: number;
  tier: 'elite' | 'pro' | 'free';
  gameTime: string;
  analysis?: string;
  expectedValue?: number;
  edge?: number;
}

export interface BettingSheetOptions {
  title: string;
  date: string;
  picks: ExportPick[];
  includeAnalysis: boolean;
  includeQRCode: boolean;
  branding: 'minimal' | 'full';
}

export interface CsvExportOptions {
  picks: ExportPick[];
  includeMetadata: boolean;
  dateRange?: { start: string; end: string };
}

export class ExportService {
  /**
   * Generate PDF betting sheet
   */
  async generateBettingSheet(options: BettingSheetOptions): Promise<Buffer> {
    const doc = new jsPDF();
    const { title, date, picks, includeAnalysis, branding } = options;

    // Header
    if (branding === 'full') {
      doc.setFontSize(24);
      doc.setTextColor(33, 150, 243);
      doc.text('PROGNO PICKS', 105, 20, { align: 'center' });
    }

    doc.setFontSize(14);
    doc.setTextColor(0, 0, 0);
    doc.text(title, 105, 35, { align: 'center' });
    doc.setFontSize(10);
    doc.text(date, 105, 42, { align: 'center' });

    // Group by tier
    const elitePicks = picks.filter(p => p.tier === 'elite');
    const proPicks = picks.filter(p => p.tier === 'pro');
    const freePicks = picks.filter(p => p.tier === 'free');

    let currentY = 50;

    // Elite Picks
    if (elitePicks.length > 0) {
      currentY = this.renderTierSection(doc, 'ELITE PICKS', elitePicks, currentY, '#FFD700');
    }

    // Pro Picks
    if (proPicks.length > 0) {
      currentY = this.renderTierSection(doc, 'PRO PICKS', proPicks, currentY, '#C0C0C0');
    }

    // Free Picks
    if (freePicks.length > 0) {
      currentY = this.renderTierSection(doc, 'FREE PICKS', freePicks, currentY, '#CD7F32');
    }

    // Summary
    this.renderSummary(doc, picks, currentY + 10);

    // Footer
    doc.setFontSize(8);
    doc.setTextColor(128, 128, 128);
    doc.text('Generated by PROGNO AI | Bet responsibly', 105, 280, { align: 'center' });

    return Buffer.from(doc.output('arraybuffer'));
  }

  /**
   * Generate CSV export
   */
  generateCSV(options: CsvExportOptions): string {
    const { picks, includeMetadata } = options;

    // Header
    let csv = 'Date,Sport,Game,Pick,Type,Odds,Confidence,Tier,Expected Value,Edge\n';

    // Data rows
    for (const pick of picks) {
      const row = [
        pick.gameTime,
        pick.sport,
        pick.game,
        pick.pick,
        pick.pickType,
        pick.odds,
        pick.confidence,
        pick.tier,
        pick.expectedValue || '',
        pick.edge || '',
      ].map(field => `"${field}"`).join(',');

      csv += row + '\n';
    }

    // Metadata section
    if (includeMetadata) {
      csv += '\n\nSUMMARY\n';
      csv += `Total Picks,${picks.length}\n`;
      csv += `Elite Picks,${picks.filter(p => p.tier === 'elite').length}\n`;
      csv += `Pro Picks,${picks.filter(p => p.tier === 'pro').length}\n`;
      csv += `Free Picks,${picks.filter(p => p.tier === 'free').length}\n`;
      csv += `Average Confidence,${(picks.reduce((s, p) => s + p.confidence, 0) / picks.length).toFixed(1)}%\n`;
      csv += `Average Edge,${(picks.reduce((s, p) => s + (p.edge || 0), 0) / picks.length).toFixed(1)}%\n`;
    }

    return csv;
  }

  /**
   * Generate individual pick card (for sharing)
   */
  generatePickCard(pick: ExportPick): Buffer {
    const doc = new jsPDF({
      orientation: 'landscape',
      unit: 'mm',
      format: [85.6, 53.98], // Business card size
    });

    // Background based on tier
    const tierColor = this.getTierColor(pick.tier);
    doc.setFillColor(tierColor.r, tierColor.g, tierColor.b);
    doc.rect(0, 0, 85.6, 15, 'F');

    // Header
    doc.setFontSize(10);
    doc.setTextColor(255, 255, 255);
    doc.text(`${pick.tier.toUpperCase()} PICK`, 5, 10);

    // Confidence badge
    doc.setFillColor(255, 255, 255);
    doc.roundedRect(60, 5, 20, 8, 2, 2, 'F');
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(8);
    doc.text(`${pick.confidence}%`, 70, 10, { align: 'center' });

    // Content
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(9);
    doc.text(pick.sport, 5, 22);
    doc.setFontSize(8);
    doc.text(pick.game, 5, 27);

    doc.setFontSize(11);
    doc.setFont('helvetica', 'bold');
    doc.text(pick.pick, 5, 35);
    doc.setFont('helvetica', 'normal');

    doc.setFontSize(10);
    doc.text(this.formatOdds(pick.odds), 5, 42);

    // Edge indicator
    if (pick.edge) {
      doc.setFillColor(76, 175, 80);
      doc.roundedRect(60, 38, 20, 6, 1, 1, 'F');
      doc.setTextColor(255, 255, 255);
      doc.setFontSize(7);
      doc.text(`+${pick.edge}% edge`, 70, 42, { align: 'center' });
    }

    // Footer
    doc.setTextColor(128, 128, 128);
    doc.setFontSize(6);
    doc.text('PROGNO.AI', 5, 50);
    doc.text(pick.gameTime, 75, 50, { align: 'right' });

    return Buffer.from(doc.output('arraybuffer'));
  }

  /**
   * Generate printable daily sheet (simplified)
   */
  generateDailySheet(picks: ExportPick[]): string {
    const html = `
<!DOCTYPE html>
<html>
<head>
  <style>
    body { font-family: Arial, sans-serif; margin: 20px; }
    .header { text-align: center; margin-bottom: 20px; }
    .tier { margin-bottom: 15px; }
    .tier-header { font-weight: bold; font-size: 18px; padding: 8px; }
    .elite { background: #FFD700; }
    .pro { background: #C0C0C0; }
    .free { background: #CD7F32; }
    .pick { border: 1px solid #ddd; padding: 10px; margin: 5px 0; }
    .pick-header { font-weight: bold; }
    .odds { float: right; font-weight: bold; color: #2196F3; }
    .confidence { display: inline-block; padding: 2px 8px; border-radius: 10px; font-size: 12px; }
    .high { background: #4CAF50; color: white; }
    .med { background: #FF9800; color: white; }
    .low { background: #f44336; color: white; }
    .analysis { font-size: 11px; color: #666; margin-top: 5px; }
    .summary { margin-top: 20px; padding: 10px; background: #f5f5f5; }
    @media print {
      body { margin: 10px; }
      .no-print { display: none; }
    }
  </style>
</head>
<body>
  <div class="header">
    <h1>PROGNO PICKS - ${new Date().toLocaleDateString()}</h1>
    <p class="no-print"><button onclick="window.print()">Print Sheet</button></p>
  </div>
  
  ${this.renderTierHTML(picks.filter(p => p.tier === 'elite'), 'elite', 'ELITE PICKS')}
  ${this.renderTierHTML(picks.filter(p => p.tier === 'pro'), 'pro', 'PRO PICKS')}
  ${this.renderTierHTML(picks.filter(p => p.tier === 'free'), 'free', 'FREE PICKS')}
  
  <div class="summary">
    <strong>Summary:</strong> ${picks.length} picks | 
    Elite: ${picks.filter(p => p.tier === 'elite').length} | 
    Pro: ${picks.filter(p => p.tier === 'pro').length} | 
    Free: ${picks.filter(p => p.tier === 'free').length}
  </div>
</body>
</html>`;

    return html;
  }

  private renderTierSection(
    doc: jsPDF,
    title: string,
    picks: ExportPick[],
    startY: number,
    color: string
  ): number {
    // Section header
    doc.setFillColor(color);
    doc.rect(10, startY, 190, 10, 'F');
    doc.setFontSize(12);
    doc.setTextColor(0, 0, 0);
    doc.text(title, 15, startY + 7);

    // Table
    const tableData = picks.map(p => [
      p.sport,
      p.game,
      p.pick,
      this.formatOdds(p.odds),
      `${p.confidence}%`,
      p.edge ? `+${p.edge}%` : '',
    ]);

    (doc as any).autoTable({
      startY: startY + 12,
      head: [['Sport', 'Game', 'Pick', 'Odds', 'Conf', 'Edge']],
      body: tableData,
      theme: 'grid',
      headStyles: { fillColor: [66, 66, 66] },
      styles: { fontSize: 9 },
      columnStyles: {
        0: { cellWidth: 25 },
        1: { cellWidth: 50 },
        2: { cellWidth: 50 },
        3: { cellWidth: 20 },
        4: { cellWidth: 20 },
        5: { cellWidth: 25 },
      },
    });

    return (doc as any).lastAutoTable.finalY + 5;
  }

  private renderSummary(doc: jsPDF, picks: ExportPick[], y: number): void {
    const elite = picks.filter(p => p.tier === 'elite').length;
    const pro = picks.filter(p => p.tier === 'pro').length;
    const free = picks.filter(p => p.tier === 'free').length;
    const avgConf = (picks.reduce((s, p) => s + p.confidence, 0) / picks.length).toFixed(1);

    doc.setFontSize(11);
    doc.setTextColor(0, 0, 0);
    doc.text('DAILY SUMMARY', 105, y, { align: 'center' });

    doc.setFontSize(10);
    doc.text(`Total Picks: ${picks.length}`, 20, y + 10);
    doc.text(`Elite: ${elite} | Pro: ${pro} | Free: ${free}`, 20, y + 18);
    doc.text(`Average Confidence: ${avgConf}%`, 20, y + 26);

    // Tier distribution chart (simple)
    const chartY = y + 35;
    const total = picks.length || 1;
    
    // Elite bar
    doc.setFillColor(255, 215, 0);
    doc.rect(20, chartY, (elite / total) * 100, 8, 'F');
    
    // Pro bar
    doc.setFillColor(192, 192, 192);
    doc.rect(20 + (elite / total) * 100, chartY, (pro / total) * 100, 8, 'F');
    
    // Free bar
    doc.setFillColor(205, 127, 50);
    doc.rect(20 + ((elite + pro) / total) * 100, chartY, (free / total) * 100, 8, 'F');
  }

  private renderTierHTML(picks: ExportPick[], tierClass: string, title: string): string {
    if (picks.length === 0) return '';

    const picksHTML = picks.map(p => {
      const confClass = p.confidence >= 80 ? 'high' : p.confidence >= 65 ? 'med' : 'low';
      return `
        <div class="pick">
          <div class="pick-header">
            ${p.sport} - ${p.game}
            <span class="odds">${this.formatOdds(p.odds)}</span>
          </div>
          <div>
            <strong>${p.pick}</strong>
            <span class="confidence ${confClass}">${p.confidence}%</span>
            ${p.edge ? `<span style="color: #4CAF50; font-size: 12px;">+${p.edge}% edge</span>` : ''}
          </div>
          ${p.analysis ? `<div class="analysis">${p.analysis.substring(0, 100)}...</div>` : ''}
        </div>
      `;
    }).join('');

    return `
      <div class="tier">
        <div class="tier-header ${tierClass}">${title}</div>
        ${picksHTML}
      </div>
    `;
  }

  private formatOdds(odds: number): string {
    return odds > 0 ? `+${odds}` : odds.toString();
  }

  private getTierColor(tier: string): { r: number; g: number; b: number } {
    switch (tier) {
      case 'elite': return { r: 255, g: 215, b: 0 };
      case 'pro': return { r: 192, g: 192, b: 192 };
      case 'free': return { r: 205, g: 127, b: 50 };
      default: return { r: 128, g: 128, b: 128 };
    }
  }
}

export default ExportService;
