/**
 * Legal Disclaimers
 * Required disclaimers for sports betting predictions and financial advice
 */

export const LEGAL_DISCLAIMERS = {
  prediction: `
**DISCLAIMER - NOT FINANCIAL ADVICE**

The predictions, analyses, and recommendations provided by this API are for informational and entertainment purposes only. They do not constitute financial, investment, or legal advice.

**IMPORTANT WARNINGS:**

1. **No Guarantees**: Past performance does not guarantee future results. All predictions are probabilistic estimates, not certainties.

2. **Gambling Risks**: Sports betting involves substantial risk of loss. Only wager money you can afford to lose.

3. **No Liability**: The operators of this service assume no liability for any losses incurred from following predictions or recommendations.

4. **Regulatory Compliance**: Users are responsible for ensuring their use of this service complies with all applicable local, state, and federal laws regarding sports betting and gambling.

5. **No Endorsement**: Predictions are generated by algorithmic models and do not represent endorsements of any team, player, or outcome.

6. **Data Accuracy**: While we strive for accuracy, we make no warranties regarding the completeness, reliability, or accuracy of data used in predictions.

7. **User Responsibility**: Users are solely responsible for their betting decisions and should conduct their own research before placing any wagers.

**By using this API, you acknowledge that you have read, understood, and agree to these terms.**
  `.trim(),

  arbitrage: `
**ARBITRAGE DISCLAIMER**

Arbitrage opportunities are time-sensitive and may expire before execution. The opportunities displayed are based on data available at the time of detection and may no longer be valid.

**Risks:**
- Odds change rapidly; opportunities may disappear before you can place bets
- Sportsbooks may limit or cancel bets if they detect arbitrage betting
- Account restrictions may apply
- Minimum stake requirements may affect profitability

**User Responsibility:**
- Verify all odds and terms before placing bets
- Ensure you have accounts with multiple sportsbooks
- Understand the risks of account limitations
- This service does not guarantee arbitrage opportunities will remain available
  `.trim(),

  simulation: `
**SIMULATION DISCLAIMER**

Monte Carlo simulations are probabilistic models based on historical data and statistical assumptions. Results are estimates, not guarantees.

**Limitations:**
- Simulations cannot account for all real-world variables (injuries, weather changes, referee decisions, etc.)
- Results are based on the data and parameters provided
- Past performance does not guarantee future results
- Simulations are computational estimates, not actual game outcomes

**Use at Your Own Risk:**
Simulation results should be used as one factor in decision-making, not as the sole basis for betting decisions.
  `.trim(),

  claudeEffect: `
**CLAUDE EFFECT DISCLAIMER**

The Claude Effect is an experimental AI-powered prediction enhancement system. It incorporates sentiment analysis, narrative detection, and market intelligence to adjust base probabilities.

**Important Notes:**
- The Claude Effect is a probability modifier, not a guarantee
- AI models may have biases or limitations
- Market signals and sentiment can change rapidly
- Results are probabilistic estimates, not certainties

**Experimental Nature:**
This system is continuously being refined and improved. Results may vary as the model learns and adapts.
  `.trim(),
};

/**
 * Get appropriate disclaimer for an endpoint
 */
export function getDisclaimer(endpoint: string): string {
  if (endpoint.includes('prediction') || endpoint.includes('predict')) {
    return LEGAL_DISCLAIMERS.prediction;
  }
  if (endpoint.includes('arbitrage') || endpoint.includes('arb')) {
    return LEGAL_DISCLAIMERS.arbitrage;
  }
  if (endpoint.includes('simulation') || endpoint.includes('simulate')) {
    return LEGAL_DISCLAIMERS.simulation;
  }
  if (endpoint.includes('claude-effect') || endpoint.includes('claude')) {
    return LEGAL_DISCLAIMERS.claudeEffect;
  }
  return LEGAL_DISCLAIMERS.prediction; // Default
}

