/**
 * Legal Service
 * Alabama-compliant legal disclaimers and consent management
 */

export type LegalContext = 'simulation' | 'arbitrage' | 'general' | 'prediction' | 'claude-effect';

export interface LegalDisclaimer {
  text: string;
  context: LegalContext;
  alabamaCompliance: boolean;
  version: string;
  fullText?: string; // Full detailed disclaimer
}

/**
 * Get legal disclaimer for a specific context
 */
export function getLegalDisclaimer(context: LegalContext): LegalDisclaimer {
  const base = "CEVICT FLUX v2.0: FOR ENTERTAINMENT & INFORMATIONAL PURPOSES ONLY. ";

  const disclaimers: Record<LegalContext, { short: string; full: string }> = {
    simulation: {
      short: `${base}Results are generated via Monte Carlo statistical modeling and do not guarantee future outcomes. Past performance is not indicative of future results. Simulations are based on 2025 SportsBlaze historical data and may not account for all real-world variables (injuries, weather changes, referee decisions, etc.).`,
      full: `${base}

**SIMULATION DISCLAIMER - ALABAMA COMPLIANCE**

Results are generated via Monte Carlo statistical modeling and do not guarantee future outcomes. Past performance is not indicative of future results. Simulations are based on 2025 SportsBlaze historical data and may not account for all real-world variables (injuries, weather changes, referee decisions, etc.).

**ALABAMA-SPECIFIC NOTICE:**
This service provides statistical analysis tools intended to enhance skill-based assessment of sporting events. This service does not constitute a 'gambling device' under Alabama Code § 13A-12-20. No legal sports betting framework exists in-state as of 2025; use of this data for illegal wagering is strictly prohibited.

**LIMITATIONS:**
- Simulations cannot account for all real-world variables
- Results are computational estimates, not actual game outcomes
- Past performance does not guarantee future results
- Use at your own risk`
    },

    arbitrage: {
      short: `${base}Odds are subject to rapid market fluctuation. Cevict Flux does not guarantee the availability of these lines at the time of placement. Arbitrage opportunities are time-sensitive and may expire before execution. Sportsbooks may limit or cancel bets if they detect arbitrage betting.`,
      full: `${base}

**ARBITRAGE DISCLAIMER - ALABAMA COMPLIANCE**

Odds are subject to rapid market fluctuation. Cevict Flux does not guarantee the availability of these lines at the time of placement. Arbitrage opportunities are time-sensitive and may expire before execution. Sportsbooks may limit or cancel bets if they detect arbitrage betting.

**ALABAMA-SPECIFIC NOTICE:**
Cevict Flux is a data provider, not a sportsbook or brokerage. We do not accept, facilitate, or settle wagers. Any engagement with third-party sportsbooks or prediction markets is at the user's sole discretion. No legal sports betting framework exists in Alabama as of 2025.

**RISKS:**
- Odds change rapidly; opportunities may disappear before you can place bets
- Sportsbooks may limit or cancel bets if they detect arbitrage betting
- Account restrictions may apply
- Minimum stake requirements may affect profitability`
    },

    general: {
      short: `${base}Not financial advice. User assumes all risk for wagering activities. This service does not constitute a 'gambling device' under Alabama Code § 13A-12-20.`,
      full: `${base}

**GENERAL DISCLAIMER - ALABAMA COMPLIANCE**

Not financial advice. User assumes all risk for wagering activities. This service does not constitute a 'gambling device' under Alabama Code § 13A-12-20.

**ALABAMA-SPECIFIC NOTICE:**
The Progno API provides statistical analysis tools intended to enhance the user's skill-based assessment of sporting events. This service does not constitute a 'gambling device' under Alabama Code § 13A-12-20. No legal sports betting framework exists in-state as of 2025; use of this data for illegal wagering is strictly prohibited.

**IMPORTANT WARNINGS:**
1. No Guarantees: Past performance does not guarantee future results
2. Gambling Risks: Sports betting involves substantial risk of loss
3. No Liability: Operators assume no liability for losses
4. Regulatory Compliance: Users responsible for legal compliance
5. No Endorsement: Predictions are algorithmic, not endorsements`
    },

    prediction: {
      short: `${base}Predictions are probabilistic estimates generated by algorithmic models. They do not represent endorsements of any team, player, or outcome. All predictions are subject to the limitations of historical data and statistical models.`,
      full: `${base}

**PREDICTION DISCLAIMER - ALABAMA COMPLIANCE**

Predictions are probabilistic estimates generated by algorithmic models. They do not represent endorsements of any team, player, or outcome. All predictions are subject to the limitations of historical data and statistical models.

**ALABAMA-SPECIFIC NOTICE:**
This service provides statistical analysis tools intended to enhance skill-based assessment. This service does not constitute a 'gambling device' under Alabama Code § 13A-12-20. AI and automated predictions are subject to 'hallucinations' or data lag. Under the Alabama Deceptive Trade Practices Act, users acknowledge that no prediction is 'risk-free'. No legal sports betting framework exists in-state as of 2025.

**LIMITATIONS:**
- Predictions are probabilistic estimates, not certainties
- Models may have biases or limitations
- Data accuracy not guaranteed
- User assumes all risk`
    },

    'claude-effect': {
      short: `${base}The Claude Effect is an experimental AI-powered prediction enhancement system. AI models may have biases or limitations. Results are probabilistic estimates, not certainties.`,
      full: `${base}

**CLAUDE EFFECT DISCLAIMER - ALABAMA COMPLIANCE**

The Claude Effect is an experimental AI-powered prediction enhancement system. AI models may have biases or limitations. Results are probabilistic estimates, not certainties.

**ALABAMA-SPECIFIC NOTICE:**
AI and automated predictions are subject to 'hallucinations' or data lag. Under the Alabama Deceptive Trade Practices Act, users acknowledge that no prediction is 'risk-free'. This service does not constitute a 'gambling device' under Alabama Code § 13A-12-20.

**EXPERIMENTAL NATURE:**
- The Claude Effect is a probability modifier, not a guarantee
- AI models may have biases or limitations
- Market signals and sentiment can change rapidly
- System is continuously being refined and improved`
    },
  };

  const disclaimer = disclaimers[context];

  return {
    text: `${disclaimer.short} If you or someone you know has a gambling problem, call 1-800-GAMBLER.`,
    fullText: `${disclaimer.full}

If you or someone you know has a gambling problem, call 1-800-GAMBLER.`,
    context,
    alabamaCompliance: true,
    version: '2.0.0-2025-AL',
  };
}

/**
 * Get Alabama-specific legal clauses for Terms of Service
 */
export function getAlabamaLegalClauses(): {
  skillVsChance: string;
  noBrokerage: string;
  algorithmDisclaimer: string;
} {
  return {
    skillVsChance: `Cevict Flux provides statistical analysis tools intended to enhance the user's skill-based assessment of sporting events. This service does not constitute a 'gambling device' under Alabama Code § 13A-12-20.`,

    noBrokerage: `Cevict Flux is a data provider, not a sportsbook or brokerage. We do not accept, facilitate, or settle wagers. Any engagement with third-party sportsbooks or prediction markets (e.g., FanDuel Predicts) is at the user's sole discretion.`,

    algorithmDisclaimer: `AI and automated predictions are subject to 'hallucinations' or data lag. Under the Alabama Deceptive Trade Practices Act, users acknowledge that no prediction is 'risk-free'.`,
  };
}

/**
 * Generate metadata disclaimer for API responses
 */
export function generateMetadataDisclaimer(context: LegalContext): {
  disclaimer: string;
  processed_at: string;
  alabama_notice: string;
} {
  const disclaimer = getLegalDisclaimer(context);

  return {
    disclaimer: disclaimer.text,
    processed_at: new Date().toISOString(),
    alabama_notice: "Alabama residents: No legal sports betting framework exists in-state as of 2025; use of this data for illegal wagering is strictly prohibited.",
  };
}

