-- Migration for Age Verification and Legal Compliance
-- Critical for 2026 tobacco/nicotine regulations

-- Add verification fields to unified_users table
ALTER TABLE unified_users 
ADD COLUMN IF NOT EXISTS is_age_verified BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS verification_id TEXT,
ADD COLUMN IF NOT EXISTS verification_method TEXT, -- 'soft_gate', 'database', 'manual_review'
ADD COLUMN IF NOT EXISTS verification_status TEXT DEFAULT 'unverified', -- 'unverified', 'approved', 'pending', 'rejected'
ADD COLUMN IF NOT EXISTS verified_at TIMESTAMP WITH TIME ZONE,
ADD COLUMN IF NOT EXISTS legal_address JSONB, -- Store legal address for Jenkins Act
ADD COLUMN IF NOT EXISTS date_of_birth DATE,
ADD COLUMN IF NOT EXISTS id_verification_url TEXT, -- URL to stored ID document
ADD COLUMN IF NOT EXISTS selfie_verification_url TEXT, -- URL to stored selfie
ADD COLUMN IF NOT EXISTS manual_review_required BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS compliance_agreed_at TIMESTAMP WITH TIME ZONE, -- When user agreed to terms
ADD COLUMN IF NOT EXISTS last_compliance_check TIMESTAMP WITH TIME ZONE;

-- Create verification_attempts table for audit trail
CREATE TABLE IF NOT EXISTS verification_attempts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT REFERENCES unified_users(id),
  verification_id TEXT NOT NULL,
  method TEXT NOT NULL, -- 'soft_gate', 'database', 'manual_review'
  status TEXT NOT NULL, -- 'approved', 'pending', 'rejected', 'manual_review'
  request_data JSONB,
  response_data JSONB,
  ip_address INET,
  user_agent TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create jenkins_act_reports table for federal compliance
CREATE TABLE IF NOT EXISTS jenkins_act_reports (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT REFERENCES unified_users(id),
  order_id TEXT,
  report_date DATE NOT NULL,
  customer_name TEXT NOT NULL,
  customer_address TEXT NOT NULL,
  customer_city TEXT NOT NULL,
  customer_state TEXT NOT NULL,
  customer_zip TEXT NOT NULL,
  product_type TEXT NOT NULL, -- 'cigars', 'smokeless_tobacco', 'vaping', 'hemp'
  tobacco_weight DECIMAL(10,3), -- in ounces
  order_total DECIMAL(10,2),
  shipping_address TEXT,
  reported_to_state BOOLEAN DEFAULT false,
  state_report_date DATE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create compliance_logs table for audit trail
CREATE TABLE IF NOT EXISTS compliance_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT REFERENCES unified_users(id),
  action TEXT NOT NULL, -- 'age_gate_passed', 'verification_attempted', 'purchase_attempted', etc.
  details JSONB,
  ip_address INET,
  user_agent TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create felony_warnings table for restricted products
CREATE TABLE IF NOT EXISTS felony_warnings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  state_code TEXT NOT NULL,
  county TEXT,
  city TEXT,
  product_type TEXT NOT NULL, -- 'vape', 'smokable_hemp', etc.
  restriction_level TEXT NOT NULL, -- 'felony', 'misdemeanor', 'restricted'
  law_reference TEXT,
  effective_date DATE,
  warning_message TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  UNIQUE(state_code, county, product_type)
);

-- Add indexes for performance
CREATE INDEX IF NOT EXISTS idx_unified_users_is_age_verified ON unified_users(is_age_verified);
CREATE INDEX IF NOT EXISTS idx_unified_users_verification_status ON unified_users(verification_status);
CREATE INDEX IF NOT EXISTS idx_unified_users_verified_at ON unified_users(verified_at);
CREATE INDEX IF NOT EXISTS idx_verification_attempts_user_id ON verification_attempts(user_id);
CREATE INDEX IF NOT EXISTS idx_verification_attempts_status ON verification_attempts(status);
CREATE INDEX IF NOT EXISTS idx_verification_attempts_created_at ON verification_attempts(created_at);
CREATE INDEX IF NOT EXISTS idx_jenkins_act_reports_report_date ON jenkins_act_reports(report_date);
CREATE INDEX IF NOT EXISTS idx_jenkins_act_reports_user_id ON jenkins_act_reports(user_id);
CREATE INDEX IF NOT EXISTS idx_compliance_logs_user_id ON compliance_logs(user_id);
CREATE INDEX IF NOT EXISTS idx_compliance_logs_action ON compliance_logs(action);
CREATE INDEX IF NOT EXISTS idx_felony_warnings_state_product ON felony_warnings(state_code, product_type);

-- Insert initial felony warnings for high-risk areas (Alabama HB 445)
INSERT INTO felony_warnings (state_code, product_type, restriction_level, law_reference, effective_date, warning_message) VALUES
('AL', 'vape', 'felony', 'HB 445', '2025-01-01', 'WARNING: Under Alabama HB 445, certain vaping products are classified as Class C felonies. Possession or distribution may result in severe penalties including imprisonment.'),
('AL', 'smokable_hemp', 'felony', 'HB 445', '2025-01-01', 'WARNING: Under Alabama HB 445, smokable hemp products are classified as Class C felonies. Possession or distribution may result in severe penalties including imprisonment.'),
('FL', 'vape', 'restricted', 'FL Stat 386.203', '2024-07-01', 'WARNING: Florida has restrictions on vaping products in certain areas. Check local ordinances before possession or use.'),
('MS', 'vape', 'misdemeanor', 'MS Code 97-32-29', '2024-01-01', 'WARNING: Mississippi classifies certain vaping products as misdemeanors. Check local restrictions.'),
('LA', 'vape', 'restricted', 'LA RS 40:1300', '2024-06-01', 'WARNING: Louisiana has specific restrictions on vaping products. Verify local compliance.')
ON CONFLICT (state_code, product_type) DO NOTHING;

-- Enable Row Level Security
ALTER TABLE verification_attempts ENABLE ROW LEVEL SECURITY;
ALTER TABLE jenkins_act_reports ENABLE ROW LEVEL SECURITY;
ALTER TABLE compliance_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE felony_warnings ENABLE ROW LEVEL SECURITY;

-- RLS Policies
CREATE POLICY "Users can view own verification attempts" ON verification_attempts 
FOR SELECT USING (auth.uid()::text = user_id);

CREATE POLICY "Service role full access verification attempts" ON verification_attempts 
FOR ALL USING (auth.jwt()->>'role' = 'service_role');

CREATE POLICY "Users can view own jenkins act reports" ON jenkins_act_reports 
FOR SELECT USING (auth.uid()::text = user_id);

CREATE POLICY "Service role full access jenkins act reports" ON jenkins_act_reports 
FOR ALL USING (auth.jwt()->>'role' = 'service_role');

CREATE POLICY "Users can view own compliance logs" ON compliance_logs 
FOR SELECT USING (auth.uid()::text = user_id);

CREATE POLICY "Service role full access compliance logs" ON compliance_logs 
FOR ALL USING (auth.jwt()->>'role' = 'service_role');

CREATE POLICY "Public read access felony warnings" ON felony_warnings 
FOR SELECT USING (true);

CREATE POLICY "Service role full access felony warnings" ON felony_warnings 
FOR ALL USING (auth.jwt()->>'role' = 'service_role');

-- Create function to log compliance events
CREATE OR REPLACE FUNCTION log_compliance_event(
  p_user_id TEXT,
  p_action TEXT,
  p_details JSONB DEFAULT NULL,
  p_ip_address INET DEFAULT NULL,
  p_user_agent TEXT DEFAULT NULL
) RETURNS VOID AS $$
BEGIN
  INSERT INTO compliance_logs (user_id, action, details, ip_address, user_agent)
  VALUES (p_user_id, p_action, p_details, p_ip_address, p_user_agent);
END;
$$ LANGUAGE plpgsql;

-- Create function to check felony warnings
CREATE OR REPLACE FUNCTION check_felony_warnings(
  p_state_code TEXT,
  p_product_type TEXT
) RETURNS TABLE (
  restriction_level TEXT,
  warning_message TEXT,
  law_reference TEXT
) AS $$
BEGIN
  RETURN QUERY
  SELECT fw.restriction_level, fw.warning_message, fw.law_reference
  FROM felony_warnings fw
  WHERE fw.state_code = p_state_code 
    AND fw.product_type = p_product_type;
END;
$$ LANGUAGE plpgsql;

-- Create view for compliance dashboard
CREATE OR REPLACE VIEW compliance_dashboard AS
SELECT 
  (SELECT COUNT(*) FROM unified_users WHERE is_age_verified = true) as verified_users,
  (SELECT COUNT(*) FROM verification_attempts WHERE created_at >= CURRENT_DATE - INTERVAL '7 days') as verification_attempts_week,
  (SELECT COUNT(*) FROM verification_attempts WHERE status = 'approved' AND created_at >= CURRENT_DATE - INTERVAL '7 days') as successful_verifications_week,
  (SELECT COUNT(*) FROM compliance_logs WHERE created_at >= CURRENT_DATE - INTERVAL '24 hours') as compliance_events_24h,
  (SELECT COUNT(*) FROM jenkins_act_reports WHERE report_date >= CURRENT_DATE - INTERVAL '30 days' AND NOT reported_to_state) as pending_reports;

-- Grant access to compliance dashboard
GRANT SELECT ON compliance_dashboard TO service_role;
GRANT SELECT ON compliance_dashboard TO authenticated;

-- Add trigger for automatic compliance logging
CREATE OR REPLACE FUNCTION trigger_compliance_logging()
RETURNS TRIGGER AS $$
BEGIN
  IF TG_OP = 'INSERT' THEN
    PERFORM log_compliance_event(
      NEW.id::text,
      'user_updated',
      jsonb_build_object('verification_status', NEW.verification_status),
      inet_client_addr(),
      current_setting('request.headers')::json->>'user-agent'
    );
    RETURN NEW;
  END IF;
  RETURN NULL;
END;
$$ LANGUAGE plpgsql;

-- Create trigger for user verification updates
DROP TRIGGER IF EXISTS trigger_user_verification_update ON unified_users;
CREATE TRIGGER trigger_user_verification_update
  AFTER UPDATE OF verification_status ON unified_users
  FOR EACH ROW
  WHEN (OLD.verification_status IS DISTINCT FROM NEW.verification_status)
  EXECUTE FUNCTION trigger_compliance_logging();
