-- Migration for bot-related tables
-- These tables support the daily bot functionality

-- Bot run logs table
CREATE TABLE IF NOT EXISTS bot_run_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  run_date TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  success BOOLEAN NOT NULL,
  duration_ms INTEGER NOT NULL,
  results JSONB,
  errors TEXT[],
  config JSONB,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Bot settings table
CREATE TABLE IF NOT EXISTS bot_settings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  key TEXT NOT NULL UNIQUE,
  value TEXT NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Bot source updates tracking
CREATE TABLE IF NOT EXISTS bot_source_updates (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source_name TEXT NOT NULL,
  last_update TIMESTAMP WITH TIME ZONE,
  last_successful_update TIMESTAMP WITH TIME ZONE,
  update_count INTEGER DEFAULT 0,
  error_count INTEGER DEFAULT 0,
  last_error TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Daily analytics table
CREATE TABLE IF NOT EXISTS daily_analytics (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  date DATE NOT NULL UNIQUE,
  total_users INTEGER DEFAULT 0,
  active_users INTEGER DEFAULT 0,
  total_laws INTEGER DEFAULT 0,
  total_places INTEGER DEFAULT 0,
  total_bookmarks INTEGER DEFAULT 0,
  total_corrections INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Analytics trends table
CREATE TABLE IF NOT EXISTS analytics_trends (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  metric TEXT NOT NULL,
  value DECIMAL(10,2) NOT NULL,
  date DATE NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  UNIQUE(metric, date)
);

-- Daily summaries table
CREATE TABLE IF NOT EXISTS daily_summaries (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  date DATE NOT NULL UNIQUE,
  metrics JSONB,
  changes JSONB,
  generated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- User sessions table (for cleanup)
CREATE TABLE IF NOT EXISTS user_sessions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT REFERENCES unified_users(id),
  session_token TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
  last_accessed TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  ip_address INET,
  user_agent TEXT
);

-- Add bot-related columns to existing tables if they don't exist
ALTER TABLE unified_users 
ADD COLUMN IF NOT EXISTS notifications_enabled BOOLEAN DEFAULT true,
ADD COLUMN IF NOT EXISTS email_notifications BOOLEAN DEFAULT true,
ADD COLUMN IF NOT EXISTS sms_notifications BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS push_notifications BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS weekly_digest BOOLEAN DEFAULT false;

-- Add indexes for performance
CREATE INDEX IF NOT EXISTS idx_bot_run_logs_run_date ON bot_run_logs(run_date);
CREATE INDEX IF NOT EXISTS idx_bot_run_logs_success ON bot_run_logs(success);
CREATE INDEX IF NOT EXISTS idx_daily_analytics_date ON daily_analytics(date);
CREATE INDEX IF NOT EXISTS idx_analytics_trends_metric_date ON analytics_trends(metric, date);
CREATE INDEX IF NOT EXISTS idx_user_sessions_user_id ON user_sessions(user_id);
CREATE INDEX IF NOT EXISTS idx_user_sessions_expires_at ON user_sessions(expires_at);

-- Insert default bot settings
INSERT INTO bot_settings (key, value) VALUES 
  ('last_law_update', '1970-01-01T00:00:00Z'),
  ('bot_enabled', 'true'),
  ('notification_batch_size', '100'),
  ('cleanup_retention_days', '365')
ON CONFLICT (key) DO NOTHING;

-- Add RLS (Row Level Security) policies
ALTER TABLE bot_run_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE bot_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE bot_source_updates ENABLE ROW LEVEL SECURITY;
ALTER TABLE daily_analytics ENABLE ROW LEVEL SECURITY;
ALTER TABLE analytics_trends ENABLE ROW LEVEL SECURITY;
ALTER TABLE daily_summaries ENABLE ROW LEVEL SECURITY;

-- Only allow service role to modify bot tables
CREATE POLICY "Service role full access" ON bot_run_logs FOR ALL USING (auth.jwt()->>'role' = 'service_role');
CREATE POLICY "Service role full access" ON bot_settings FOR ALL USING (auth.jwt()->>'role' = 'service_role');
CREATE POLICY "Service role full access" ON bot_source_updates FOR ALL USING (auth.jwt()->>'role' = 'service_role');
CREATE POLICY "Service role full access" ON daily_analytics FOR ALL USING (auth.jwt()->>'role' = 'service_role');
CREATE POLICY "Service role full access" ON analytics_trends FOR ALL USING (auth.jwt()->>'role' = 'service_role');
CREATE POLICY "Service role full access" ON daily_summaries FOR ALL USING (auth.jwt()->>'role' = 'service_role');

-- Allow authenticated users to read analytics data
CREATE POLICY "Authenticated read access" ON daily_analytics FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY "Authenticated read access" ON analytics_trends FOR SELECT USING (auth.role() = 'authenticated');

-- Create functions for bot operations
CREATE OR REPLACE FUNCTION update_bot_source_last_update(
  p_source_name TEXT,
  p_success BOOLEAN,
  p_error TEXT DEFAULT NULL
) RETURNS VOID AS $$
BEGIN
  UPDATE bot_source_updates 
  SET 
    last_update = NOW(),
    last_successful_update = CASE WHEN p_success THEN NOW() ELSE last_successful_update END,
    update_count = update_count + 1,
    error_count = CASE WHEN p_success THEN error_count ELSE error_count + 1 END,
    last_error = p_error,
    updated_at = NOW()
  WHERE source_name = p_source_name;
  
  IF NOT FOUND THEN
    INSERT INTO bot_source_updates (source_name, last_update, last_successful_update, update_count, error_count, last_error)
    VALUES (p_source_name, NOW(), CASE WHEN p_success THEN NOW() ELSE NULL END, 1, CASE WHEN p_success THEN 0 ELSE 1 END, p_error);
  END IF;
END;
$$ LANGUAGE plpgsql;

-- Create view for bot status dashboard
CREATE OR REPLACE VIEW bot_status_dashboard AS
SELECT 
  (SELECT COUNT(*) FROM bot_run_logs WHERE run_date >= CURRENT_DATE - INTERVAL '7 days') as runs_last_7_days,
  (SELECT COUNT(*) FROM bot_run_logs WHERE success = true AND run_date >= CURRENT_DATE - INTERVAL '7 days') as successful_runs_last_7_days,
  (SELECT MAX(run_date) FROM bot_run_logs) as last_run_date,
  (SELECT success FROM bot_run_logs ORDER BY run_date DESC LIMIT 1) as last_run_success,
  (SELECT AVG(duration_ms) FROM bot_run_logs WHERE run_date >= CURRENT_DATE - INTERVAL '7 days') as avg_duration_last_7_days,
  (SELECT COUNT(*) FROM unified_users WHERE notifications_enabled = true) as users_with_notifications,
  (SELECT COUNT(*) FROM sr_law_cards WHERE is_active = true) as active_laws,
  (SELECT COUNT(*) FROM sr_directory_places WHERE status = 'verified') as verified_places;

-- Grant access to the view
GRANT SELECT ON bot_status_dashboard TO authenticated;
GRANT SELECT ON bot_status_dashboard TO service_role;
